esphome:
  name: ecostat
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: 750
    then:
      - logger.log: "Booting EcoStat"
      - lambda: |-
          id(relay_heat).turn_off();
          id(relay_cooling).turn_off();
          id(relay_fan).turn_off();
      - delay: 500ms
      - script.execute: boot_beep

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino
    platform_version: 5.4.0

#logger:
 # level: VERY_VERBOSE

api:
  encryption:
    key: "BNUNV2OHOlpurcLTmR6liwqzwCM2Kmydy8xK23ZuY1g="

ota:
  password: "13371337"

script:
- id: boot_beep
  then:
    # First ^E
    - output.turn_on: buzzer
    - output.ledc.set_frequency:
        id: buzzer
        frequency: 659.25Hz  # E
    - output.set_level:
        id: buzzer
        level: "50%"
    - delay: 300ms
    - output.turn_off: buzzer

output:
  - platform: ledc
    pin: 5
    id: buzzer

wifi:
  ssid: Spires
  password: Spires54646

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xiao-Esp32C3 Fallback Hotspot"
    password: "13371337"

i2c:
  sda: 6
  scl: 7
  scan: False

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 20

  - file: "gfonts://Poppins@700"
    id: inter
    size: 10

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      float temp_celsius = id(temp).state;
      float temp_fahrenheit = (temp_celsius * 9.0 / 5.0) + 32.0;
      char temp_str[6]; // Buffer for temperature string
      dtostrf(temp_celsius, 4, 1, temp_str); // Convert Celsius to string with 1 decimal place

      it.print(0, 0, id(inter), id(ip_address).state.c_str());
      it.printf(0, 20, id(roboto), "T: %.1f  ", temp_fahrenheit);
      it.printf(70, 20, id(roboto), "H: %d", int(id(humidity).state));
      it.printf(0, 45, id(inter), "RSSI: %d", int(id(rssi).state));


sensor:
  - platform: dht
    pin: 20
    model: DHT22
    update_interval: 10s
    temperature:
      name: "EcoStat Temperature"
      id: temp
    humidity:
      name: "EcoStat Humidity"
      id: humidity
  - platform: wifi_signal
    name: "Wi-Fi Signal Strength"
    id: rssi
    update_interval: 20s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "EcoStat IP Address"
      id: ip_address
  - platform: version
    name: "EcoStat ESPHome Version"

switch:
  - platform: gpio
    id: relay_heat
    pin:
      number: 3
      mode: OUTPUT
  - platform: gpio
    id: relay_cooling
    pin:
      number: 9
      mode: OUTPUT
  - platform: gpio
    id: relay_fan
    pin:
      number: 8
      mode: OUTPUT

binary_sensor:
  - platform: gpio
    name: "Circulating Fan"
    id: momentaryswitch0
    pin:
      number: 4
      mode: INPUT_PULLUP
    on_press:
      then:
        - if:
            condition:
              switch.is_off: relay_fan
            then:
              - climate.control: 
                  id: ecostat_control
                  fan_mode: "on"
            else:
              - climate.control: 
                  id: ecostat_control
                  fan_mode: "off"        

climate:
  - platform: thermostat
    name: "EcoStat Control"
    id: ecostat_control
    sensor: temp
    min_cooling_off_time: 20s
    min_cooling_run_time: 60s
    min_heating_run_time: 60s
    min_heating_off_time: 120s
    min_fan_mode_switching_time: 20s
    min_idle_time: 3min
    visual:
      min_temperature: 60 째F
      max_temperature: 80 째F
      temperature_step:
        current_temperature: 0.1
        target_temperature: 1.0
        target_temperature_low: 68
    heat_action:
      - switch.turn_on: relay_heat
    idle_action:
      - switch.turn_off: relay_heat
      - switch.turn_off: relay_cooling
    cool_action:
      - switch.turn_on: relay_cooling
    fan_mode_on_action:
      - switch.turn_on: relay_fan
    fan_mode_off_action:
      - switch.turn_off: relay_fan
    default_preset: Normal
    preset:
      - name: Normal
        default_target_temperature_low: 75 째F
        default_target_temperature_high: 65 째F
