name: daily_task
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: INSTALL DOCKER
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          docker versionnn
