name: Test

on:
  push:
    branches:
      - main
      
  schedule:
    #UTC 0 
    - cron: '0 0 * * *'

jobs:
  lint:
    name: test_ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0

      - name: INSTALL DOCKER
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          docker version
      

      - name: SET CONFIG
        run : |
          echo "{
                    "index_name": "example",
                    "start_urls": ["https://c1ev0ps.github.io/docusaurus_wiki"],
                    "selectors": {
                      "lvl0": "header h1",
                      "lvl1": "header h2",
                      "lvl2": "header h3",
                      "lvl3": "header h4",
                      "lvl4": "header h5",
                      "lvl5": "p",
                      "text": "p"
                    }
                  }" > ~/config.json
            
            
      - name: Crawl Data
        run : |
            docker run -it --env-file=.env -e "CONFIG=$(cat  ~/config.json | jq -r tostring)" algolia/docsearch-scraper
            

          
