name: daily_task

on:
  push:
    branches:
      - main
      
  schedule:
    #UTC 0 
    - cron: '0 0 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0

      - name: INSTALL DOCKER
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          docker versionnn
            
            
      - name: Crawl Data
        run : |
            docker run -it --env-file=.env -e "CONFIG=$(cat  ~/config.json | jq -r tostring)" algolia/docsearch-scraper
            

          
