name: HTML to PDF Conversion
on:
  push:
    branches:
      - HTML_RE # 或者您希望触发工作流程的其他分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf
      
      - name: Convert HTML to PDF
        run: |
          wkhtmltopdf input.html output.pdf
      
      - name: Push PDF to repo
        env:
          PAT_TOKEN: ${{ SECRETS_SSH_PC }}
        run: |
          git config --global user.email "2768073931@qq.com"
          git config --global user.name "MatthewJeffson"
          git clone git@github.com:MatthewJeffson/test-files.git
          mkdir pdfs
          cp output.pdf pdfs/
          git add pdfs/
          git commit -m "Add generated PDF"
          git push --set-upstream origin main
