name: Typesense Docsearch Action

on:
  push:
    branches:
      - docusaurus-version  # 每个分支的推送都会触发
  pull_request:
    branches:
      - docusaurus-version  # 每个分支的 PR 都会触发

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run DocSearch Scraper
        uses: celsiusnarhwal/typesense-scraper@v2
        with:
          api-key: ${{ gFeXQFBRV08XUFOJzP1wYSlWhgcN6mbI }}
          host: sc4dhrl167jef08yp-1.a1.typesense.net
          port: 443
          protocol: https
          config: docsearch.json
